repos:
  -   repo: https://github.com/pre-commit/mirrors-isort
      rev: v5.10.1
      hooks:
        - id: isort
          additional_dependencies: [toml]
          exclude: env.py
          args: ["--profile", "black", --line-length=79]
  -   repo: https://github.com/psf/black
      rev: 22.6.0
      hooks:
        - id: black
          language_version: python3.9
          args: ["--line-length=79"]
  -   repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
      - id: flake8
        args: ["--max-line-length=99"]
        exclude: migrations