version: "3.8"
services:
  web:
    container_name: test_web
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    depends_on:
      - redis
      - db
    env_file: .env
    volumes:
      - ./audios/:/app/audios/
  redis:
    container_name: test_redis
    image: redis:6.0
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_bitwise_data:/data
  worker:
    build: .
    command: python -m saq app.worker.settings --web 
    depends_on:
      - redis
      - web
      - db
    ports:
      - 8080:8080
    env_file: .env
  db:
    container_name: test_db
    image: "postgres:13-alpine"
    volumes:
      - db_bitwise_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - 5432:5432
volumes:
  redis_bitwise_data: null
  db_bitwise_data: null