version: "3.8"
services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    depends_on:
      - redis
    env_file: .env
  redis:
    image: redis:6.0
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_bitwise_data:/data
  worker:
    build: .
    command: # write command
    depends_on:
      - redis
      - web
    env_file: .env
  db:
    image: "postgres:13-alpine"
    volumes:
      - db_bitwise_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - 5432:5432
volumes:
  redis_bitwise_data: null
  db_bitwise_data: null